websocket/account/urls.py
from django.conf.urls import url
from .views import *

from . import views

urlpatterns = [
    url(r'^register/$', UserCreateView.as_view(), name="register"),
    url(r'^login/$', UserLoginView.as_view(), name="login"),
    url(r'^logout/$', UserLogoutView.as_view(), name="logout"),
    url(r'^profile/(?P<pk>\d+)/$', UserProfileView.as_view(), name="profile"),
]

websocket/dashboard/urls.py
from django.conf.urls import url
from .views import *

from . import views

urlpatterns = [
    url(r'^$', IndexView.as_view(), name="index"),
]

websocket/share/urls.py
from django.conf.urls import url
from .views import *

from . import views

urlpatterns = [
    url(r'^qr/(?P<pk>\d+)$', QRDetailView.as_view(), name="qr_code"),
    url(r'^profile/(?P<pk>\d+)$', UserProfileView.as_view(), name="profile"),
]

websocket/websocket/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from websocket import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('dashboard.urls', namespace ="dashboard")),
    url(r'^account/', include('account.urls', namespace="account")),
    url(r'^share/', include('share.urls', namespace="share")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

websocket/account/models.py
from django.contrib.auth.models import User
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.db import models

import qrcode
import io
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse_lazy
from websocket.settings import HOST


# Create your models here.


class QRCode(models.Model):
    user = models.ForeignKey('auth.User', verbose_name=u'Usuario')
    qr_code = models.ImageField(upload_to='qrcodes', blank=True, null=True, )

    create_date = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return u'%s %s' % (self.user.first_name, self.user.last_name)

    def get_absolute_url(self):
        return reverse_lazy('share:qr_code', args=[self.pk])

    def generate_qr_code(self):
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=25,
            border=0,
        )
        qr.add_data(str(HOST) + str(reverse_lazy('share:profile', args=[self.user.pk])))
        qr.make(fit=True)

        img = qr.make_image()

        buffer = io.BytesIO()
        img.save(buffer)

        filename = "qr-code-%s.png" % self.pk

        filebuffer = InMemoryUploadedFile(buffer, None, filename, 'image/png', buffer.__sizeof__(), None)
        self.qr_code.save(filename, filebuffer)


class Scan(models.Model):
    qr_code = models.ForeignKey('QRCode', verbose_name=u'Código QR')
    ip = models.CharField(max_length=30, verbose_name=u'Dirección Ip')
    browser = models.CharField(max_length=50, verbose_name=u'Navegador')
    os = models.CharField(max_length=50, verbose_name=u'Sistema Operativo')
    create_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-create_date']

    def get_create_date_as_string(self):
        return self.create_date.strftime("%b. %-d, %Y, %-H:%M %p.")


@receiver(post_save, sender=QRCode)
def post_create_qr(sender, instance, **kwargs):
    if instance.qr_code.name is None:
        print('generate qr code')
        instance.generate_qr_code()


@receiver(post_save, sender=User)
def post_create_user(sender, instance, **kwargs):
    if not instance.qrcode_set.all():
        print('create qr Object')
        qr = QRCode.objects.create(user=instance)

websocket/share/models.py
from django.db import models

# Create your models here.

websocket/account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=30, required=True, label=u'Nombre de usuario')
    password1 = forms.CharField(widget=forms.PasswordInput, label=u'Contraseña')
    password2 = forms.CharField(widget=forms.PasswordInput, label=u'Confirmar contraseña')

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')
        help_texts = {
            'password2': 'asd',
        }

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)

        for fieldname in ['password1', 'password2']:
            self.fields[fieldname].help_text = None


class LoginForm(forms.Form):
    username = forms.CharField(max_length=30, required=True, label=u'Nombre de usuario')
    password = forms.CharField(widget=forms.PasswordInput, label=u'Contraseña')


class ProfileForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, required=True, label=u'Nombre')
    last_name = forms.CharField(max_length=30, required=True, label=u'Apellidos')
    email = forms.EmailField(max_length=50, required=True, label=u'Correo electrónico')
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

websocket/account/views.py
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.models import User

from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic

from account.forms import RegisterForm, LoginForm, ProfileForm


# Create your views here.

class UserCreateView(generic.CreateView):
    model = User
    form_class = RegisterForm
    template_name = 'account/user_form.html'
    success_url = reverse_lazy('dashboard:register_user')




class UserLoginView(UserPassesTestMixin, generic.View):
    login_url = '/'
    redirect_field_name = ''
    def get(self, request):
        return render(request, 'account/login_form.html', context={
            'form': LoginForm,
        })

    def post(self, request):
        username = self.request.POST.get('username')
        password = self.request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('dashboard:index')
        else:
            return render(request, 'account/login_form.html', context={
                'err_message': 'Credenciales invalidas.',
                'form': LoginForm
            })

    def test_func(self):
        return not self.request.user.is_authenticated


class UserLogoutView(generic.View):
    def get(self, request):
        if self.request.user.is_authenticated:
            logout(request)
        return redirect('account:login')

class UserProfileView(generic.UpdateView):
    model = User
    form_class = ProfileForm
    template_name = 'account/profile_form.html'
    success_url = '/'

websocket/dashboard/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import render
from django.views import generic


# Create your views here.

class IndexView(UserPassesTestMixin, generic.View):
    login_url = '/account/login/'
    def get(self, request):
        return render(request, 'dashboard/index.html')

    def test_func(self):
        return self.request.user.is_authenticated

websocket/share/views.py
from django.contrib.auth.models import User
from django.views import generic
from channels import Group
from account.models import QRCode, Scan
from .services import get_client_ip

import json
import user_agents


# Create your views here.

class QRDetailView(generic.DetailView):
    model = QRCode
    template_name = 'share/qrcode_detail.html'


class UserProfileView(generic.DetailView):
    model = User
    template_name = 'share/profile_detail.html'

    def get(self, request, *args, **kwargs):
        print(request.META['HTTP_USER_AGENT'])
        ua = user_agents.parse(request.META['HTTP_USER_AGENT'])
        qr = self.get_object().qrcode_set.all().first()
        scan = Scan.objects.create(
            qr_code=qr,
            ip=get_client_ip(request),
            browser=ua.browser.family,
            os=ua.os.family,
        )

        send = {
            'type': 'view',
            'ip': scan.ip,
            'browser': scan.browser,
            'os': scan.os,
            'date': scan.get_create_date_as_string(),
        }
        send = json.dumps(send)

        Group('user-%s' % self.get_object().pk).send({'text': send})
        return super().get(request, *args, **kwargs)

websocket/dashboard/templates/dashboard/index.html
{% extends 'main.html' %}
{% load static %}
{# Load the tag library #}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block body %}
  <div class="row">
    <div class="col-sm-4">
      <div class="card">
        <img class="card-img-top" src="https://placeimg.com/640/310/any" alt="Card image cap">
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><span class=""></span>@{{ request.user.username }}</li>
          <li class="list-group-item">
            {% if request.user.first_name %}
              {{ request.user.first_name }} {{ request.user.last_name }}
            {% else %}
              <span class="text-info">Debe actualizar la información de su perfil </span>
            {% endif %}
          </li>
          {% if request.user.qrcode_set.all.first.qr_code.url %}
            <li class="list-group-item">
              <div class="qr-wrapper">
                <img src="{{ request.user.qrcode_set.all.first.qr_code.url }}">
                <div class="btn-wrapper">
                  <a href="#" class="btn btn-warning"
                     data-clipboard-text="{{ HOST }}{{ request.user.qrcode_set.all.first.get_absolute_url }}">Copiar
                    enlace
                  </a>
                </div>
              </div>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
    <div class="col-sm-8">
      <h4>Visitas al perfil</h4>
      <div class="card">
        <table class="table table-responsive">
          <thead>
          <tr class="table-secondary">
            <th>IP</th>
            <th>Navegador</th>
            <th>SO</th>
            <th>Fecha</th>
          </tr>
          </thead>
          <tbody id="visits">
          {% with request.user.qrcode_set.all.first as qrcode %}
            {% if not qrcode.scan_set.all %}
              <tr id="placeholder">
                <td colspan="3" class="text-center text-muted">No hay visitas</td>
              </tr>
            {% else %}
              {% for scan in qrcode.scan_set.all %}
                <tr>
                  <td>{{ scan.ip }}</td>
                  <td>{{ scan.browser }}</td>
                  <td>{{ scan.os }}</td>
                  <td>{{ scan.get_create_date_as_string }}</td>
                </tr>
              {% endfor %}
            {% endif %}
          {% endwith %}
          </tbody>
        </table>
      </div>
    </div>
  </div>

{% endblock %}
{% block script %}
  <script src="{% static 'js/clipboard.min.js' %}"></script>
  <script>
      var clipboard = new Clipboard('*[data-clipboard-text]');
      clipboard.on('success', function (e) {
          $.notify({
              // options
              icon: 'glyphicon glyphicon-ok-circle',
              message: 'Copiado en el portapapeles'
          }, {
              // settings
              type: "warning"
          });
          e.clearSelection();
      });
  </script>

  <script src="{% static 'js/reconnecting-websocket.min.js' %}"></script>
  <script src="{% static 'js/update.js' %}"></script>

{% endblock %}

websocket/share/templates/share/profile_detail.html
{% extends 'main.html' %}

{# Load the tag library #}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block body %}
  <div class="row">
    <div class="col-md-6 ml-md-auto mr-md-auto col-xs-12">
      <div class="card text-center">
        <div class="card-body">
          <div class="text-center">
            <img src="https://placeimg.com/150/150/people" alt="Foto de perfil" class="rounded-circle">
          </div>
          <h4 class="card-title">{{ user.first_name }} {{ user.last_name }} <br>
            <small class="text-muted">@{{ user.username }}</small>
          </h4>
          <p class="card-text"><a href="mailto:{{ user.email }}">{{ user.email }}</a></p>
          <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores cum debitis,
            incidunt omnis provident sequi temporibus totam voluptatem. Debitis, earum exercitationem facilis mollitia
            nam neque numquam odio quo repellendus soluta?</p>
        </div>
      </div>
    </div>
  </div>
  <div class="blur-bg-wrapper">
    <div class="blur-bg" style="background: url('https://placeimg.com/2500/1200/nature');"></div>
  </div>
{% endblock %}

websocket/share/templates/share/qrcode_detail.html
{% extends 'main.html' %}

{# Load the tag library #}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block body %}
  <div class="row">
    <div class="col-md-6 ml-md-auto mr-md-auto col-xs-12">
      <div class="qr-wrapper alone">
        <img src="{{ qrcode.qr_code.url }}" alt="Card image cap">
      </div>
    </div>
  </div>
  <div class="blur-bg-wrapper">
    <div class="blur-bg" style="background: url('https://placeimg.com/2500/1200/nature');"></div>
  </div>
{% endblock %}

websocket/websocket/templates/main.html
{# Load the tag library #}
{% load bootstrap4 %}
{% load static %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Websocket</title>
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Websocket</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      {% block links %}
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
      {% endblock %}
    </ul>
    <ul class="navbar-nav ml-auto">
      {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a href="{% url 'account:logout' %}" class="nav-link">Cerrar Sesión</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'account:profile' request.user.pk %}" class="nav-link">Perfil</a>
        </li>
      {% else %}
        <li><a href="{% url 'account:login' %}" role="button">Iniciar Sesión</a></li>
      {% endif %}
    </ul>
  </div>
</nav>
<br>
<div class="container">
  {% block body %}{% endblock %}
</div>

<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap-notify-master/bootstrap-notify.js' %}"></script>
{% bootstrap_javascript %}
{% block script %}{% endblock %}
</body>
</html>